APP_DESCRIPTOR_MODULE_DIR := $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))

.PHONY: INSERT_CRC
POST_MAKE_ALL_RULE_HOOK: INSERT_CRC
INSERT_CRC: $(BUILDDIR)/$(PROJECT).bin
	python $(APP_DESCRIPTOR_MODULE_DIR)/crc_binary.py $(BUILDDIR)/$(PROJECT).bin $(BUILDDIR)/$(PROJECT).bin
