#include <hal.h>

void boardInit(void) {
    // SPI3
    palSetLineMode(BOARD_PAL_LINE_SPI_3_SCK, PAL_MODE_ALTERNATE(6) | PAL_STM32_OSPEED_HIGHEST | PAL_STM32_PUPDR_PULLDOWN);
    palSetLineMode(BOARD_PAL_LINE_SPI_3_MISO, PAL_MODE_ALTERNATE(6) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SPI_3_MOSI, PAL_MODE_ALTERNATE(6) | PAL_STM32_OSPEED_HIGHEST);

    // outputs
    palSetLineMode(BOARD_PAL_LINE_SPI_CS_ICM, PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_SPI_CS_MS5525DSO, PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST);
    palSetLine(BOARD_PAL_LINE_SPI_CS_ICM);
    palSetLine(BOARD_PAL_LINE_SPI_CS_MS5525DSO);

    // CAN
    palSetLineMode(BOARD_PAL_LINE_CAN_RX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_CAN_TX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);
}
