DBGDEFS = -DCH_DBG_SYSTEM_STATE_CHECK=TRUE -DCH_DBG_ENABLE_CHECKS=TRUE -DCH_DBG_ENABLE_ASSERTS=TRUE -DCH_DBG_ENABLE_TRACE=TRUE -DCH_DBG_ENABLE_STACK_CHECK=TRUE -DCH_DBG_FILL_THREADS=TRUE -DCH_CFG_OPTIMIZE_SPEED=FALSE -DCH_DBG_TRACE_MASK=CH_DBG_TRACE_MASK_ALL

UDEFS += $(DBGDEFS)
UADEFS += $(DBGDEFS)
