#include <hal.h>

void boardInit(void) {
    palSetLineMode(BOARD_PAL_LINE_SPI_SCK, PAL_MODE_ALTERNATE(6) | PAL_STM32_OSPEED_HIGHEST | PAL_STM32_PUPDR_PULLDOWN); // SPI3 SCK
    palSetLineMode(BOARD_PAL_LINE_SPI_MISO, PAL_MODE_ALTERNATE(6) | PAL_STM32_OSPEED_HIGHEST); // SPI3 MISO
    palSetLineMode(BOARD_PAL_LINE_SPI_MOSI, PAL_MODE_ALTERNATE(6) | PAL_STM32_OSPEED_HIGHEST); // SPI3 MOSI
    palSetLineMode(BOARD_PAL_LINE_SPI_UWB_CS, PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST); // UWB CS
    palSetLineMode(PAL_LINE(GPIOB, 6), PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST); // TEST POINT 1
    palSetLineMode(PAL_LINE(GPIOB, 7), PAL_MODE_OUTPUT_PUSHPULL | PAL_STM32_OSPEED_HIGHEST); // TEST POINT 2
    palSetLineMode(BOARD_PAL_LINE_UWB_IRQ, PAL_STM32_MODE_INPUT | PAL_STM32_OSPEED_HIGHEST | PAL_STM32_PUPDR_PULLDOWN); // UWB IRQ
    palSetLineMode(BOARD_PAL_LINE_CAN_RX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);
    palSetLineMode(BOARD_PAL_LINE_CAN_TX, PAL_MODE_ALTERNATE(9) | PAL_STM32_OSPEED_HIGHEST);

    palSetLineMode(LINE_UART2_RTS, PAL_MODE_ALTERNATE(7) | PAL_STM32_OSPEED_LOWEST | PAL_STM32_PUPDR_PULLUP);
    palSetLineMode(LINE_UART2_CTS, PAL_MODE_ALTERNATE(7) | PAL_STM32_OSPEED_LOWEST | PAL_STM32_PUPDR_PULLUP);
    palSetLineMode(LINE_UART2_RX, PAL_MODE_ALTERNATE(7) | PAL_STM32_OSPEED_LOWEST | PAL_STM32_PUPDR_PULLUP);
    palSetLineMode(LINE_UART2_TX, PAL_MODE_ALTERNATE(7) | PAL_STM32_OSPEED_LOWEST | PAL_STM32_PUPDR_PULLUP);

    //palSetLineMode(LINE_OTG_HS_VBUS, PAL_MODE_ALTERNATE(10) | PAL_STM32_OSPEED_LOWEST | PAL_STM32_PUPDR_PULLDOWN);
    //palSetLineMode(LINE_OTG_HS_DM, PAL_MODE_ALTERNATE(10) | PAL_STM32_OSPEED_HIGHEST | PAL_STM32_PUPDR_FLOATING);
   // palSetLineMode(LINE_OTG_HS_DP, PAL_MODE_ALTERNATE(10) | PAL_STM32_OSPEED_HIGHEST | PAL_STM32_PUPDR_FLOATING);
    palSetLineMode(LINE_SWDIO, PAL_MODE_ALTERNATE(0) | PAL_STM32_OSPEED_HIGHEST | PAL_STM32_PUPDR_PULLUP);
    palSetLineMode(LINE_SWCLK, PAL_MODE_ALTERNATE(0) | PAL_STM32_OSPEED_HIGHEST | PAL_STM32_PUPDR_PULLDOWN);

}