#pragma once

#define APP_CONFIG_BOOT_DELAY_SEC 0
#define APP_CONFIG_CAN_DEFAULT_BAUDRATE 1000000
#define APP_CONFIG_CAN_LOCAL_NODE_ID 0
#define APP_CONFIG_CAN_AUTO_BAUD_ENABLE 0

#define SHARED_APP_DESCRIPTOR_MAJOR_VERSION 1
#define SHARED_APP_DESCRIPTOR_MINOR_VERSION 0
