#pragma once

#include <modules/platform_stm32f302x8/platform_stm32f302x8.h>

#define BOARD_PAL_LINE_SPI3_SCK PAL_LINE(GPIOB,3)
#define BOARD_PAL_LINE_SPI3_MISO PAL_LINE(GPIOB,4)
#define BOARD_PAL_LINE_SPI3_MOSI PAL_LINE(GPIOB,5)
#define BOARD_PAL_LINE_SPI3_ICM_CS PAL_LINE(GPIOB,0)
#define BOARD_PAL_LINE_SPI3_FLOW_CS PAL_LINE(GPIOA,15)
#define BOARD_PAL_LINE_ICM_FSYNC PAL_LINE(GPIOA,4)
#define BOARD_PAL_LINE_FLOW_IRQ PAL_LINE(GPIOA,5)
#define BOARD_PAL_LINE_FLOW_NRST PAL_LINE(GPIOA,6)
#define BOARD_PAL_LINE_ICM_IRQ PAL_LINE(GPIOA,8)
#define BOARD_PAL_LINE_CAN_RX PAL_LINE(GPIOA,11)
#define BOARD_PAL_LINE_CAN_TX PAL_LINE(GPIOA,12)
